plugins {
    id 'net.ltgt.errorprone' version '4.2.0' apply false
}

allprojects {
    version = '0.0.1-SNAPSHOT'
    group = 'com.example.rtnt'

    // Always show stacktrace
    gradle.startParameter.showStacktrace = ShowStacktrace.ALWAYS
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'net.ltgt.errorprone'

    ext {
        springBootVersion = '4.0.6'
        bootDependencyManagement = '1.1.7'
    }

    dependencies {
        errorprone 'com.uber.nullaway:nullaway:0.13.0'
        errorprone 'com.google.errorprone:error_prone_core:2.45.0'

        implementation 'org.jspecify:jspecify:1.0.0'
    }

    configurations.all {
        resolutionStrategy {
            // prefer modules that are part of this build (multi-project or composite build) over external modules
            preferProjectModules()
        }
    }

    tasks.withType(JavaCompile) {
        options.encoding = 'UTF-8'
        options.compilerArgs << '-parameters' // Retain property names in java byte code
        options.errorprone {
            error('NullAway')
            option('NullAway:OnlyNullMarked', 'true')
            option('NullAway:JSpecifyMode', 'true')
        }
    }

    tasks.withType(Javadoc) {
        // Avoid failing builds because of java-doc errors
        options.addStringOption('Xdoclint:none', '-quiet')
        options.addStringOption('encoding', 'UTF-8')
    }

    tasks.withType(Test) {
        testLogging {
            exceptionFormat = 'full'
        }

        test.useJUnitPlatform()
    }
}
