# Spring Boot
spring.application.name=rtnt
server.port=18080

# MongoDB
spring.mongodb.uri=${MONGODB_URI:mongodb://localhost:27018/rtnt}
spring.data.mongodb.auto-index-creation=true

# Logging
logging.level.root=${LOG_LEVEL_ROOT:WARN}
logging.level.com.example.rtnt=${LOG_LEVEL_APP:WARN}
logging.level.org.mongodb.driver=${LOG_LEVEL_MONGODB_DRIVER:WARN}
logging.level.org.springframework.data.mongodb.core.MongoTemplate=WARN

# Game

## World
rtnt.startup.island-count=24
rtnt.map.width=2000
rtnt.map.height=1000

## Clock
rtnt.clock.live-enabled=true
rtnt.clock.live-interval-ms=1000

## Flush Batch Size
rtnt.clock.batch-flush-every-ticks=1000
